### ISSUE TITLE
Using `excerpt` inside a `<a>` tag can lead to an invalid HTML syntax

### ISSUE THREAD

**Issue by repinel** [bernardoamc/bernardoamc.github.io#6]
Based on [this line](https://github.com/bernardoamc/bernardoamc.github.io/blob/master/index.html#L17) from the `index.html`, if a `summary` is not provided, the `excerpt` will be used.

However, let's say that the first sentence of a post contains a link that would generate an anchor. That would result in an anchor inside another one.

**Comment by repinel** [comment]
You could just rely on the `summary` and remove the `excerpt` line.

**Comment by bernardoamc** [comment]
Makes sense. :+1:
